[package]
name = "wav-creator"
version = "0.1.0"
authors = ["Peter Aarestad <aarestad@gmail.com>"]
edition = "2021"

[dependencies]
rodio = "0.17.1"
dasp = { version = "0.11.0", features = ["all"] }
nom = "7.1.3"
anyhow = "1.0.71"
tetanes = "0.8.0"
